REDIS_EXPIRE_TIME = 60

NOT_ALL_DATA = "not all data"
NOT_ALL_DATA_CODE = 2001

PASSWORD_ERROR = "password error"
PASSWORD_ERROR_CODE = 2002

USERNAME_NOT_MATCH = "username not match"
USERNAME_NOT_MATCH_CODE = 2003

PASSWORD_NOT_MATCH = "password not match"
PASSWORD_NOT_MATCH_CODE = 2004

USER_EXIST = "user already exists"
USER_EXIST_CODE = 2005

